name: Publish Master
on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      if: github.actor != "dependabot[bot]"
    - name: Publish to Registry
      if: github.actor != "dependabot[bot]"
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lgohr/sonarqube
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
